resolver: lts-14.22
extra-deps:
  - QuickCheck-2.12.6.1
  - digit-0.8
  - generic-lens-1.2.0.1
  - hoist-error-0.2.1.0
  - hspec-2.5.9
  - hspec-core-2.5.9
  - hspec-discover-2.5.9
  - hw-balancedparens-0.3.0.4
  - hw-json-standard-cursor-0.2.1.2
  - hw-rankselect-0.13.3.2
  - natural-0.3.0.4
  - tasty-wai-0.1.1.0
  - waargonaut-0.8.0.1
  - witherable-0.3.5
  - witherable-class-0
